-- COMPREHENSIVE FIX: Run this in your Supabase SQL Editor
-- This script ensures all tables exist and links your account correctly.

-- 1. Ensure tables exist (Safety check)
DO $$ 
BEGIN
    -- Create profiles if missing
    IF NOT EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'profiles') THEN
        CREATE TABLE public.profiles (
            id uuid REFERENCES auth.users ON DELETE CASCADE NOT NULL PRIMARY KEY,
            email text UNIQUE NOT NULL,
            full_name text,
            role text CHECK (role IN ('admin', 'student', 'mess_staff')) NOT NULL DEFAULT 'student',
            created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
        );
    END IF;

    -- Create students if missing
    IF NOT EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'students') THEN
        CREATE TABLE public.students (
            id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            profile_id uuid REFERENCES public.profiles(id),
            admission_no text UNIQUE NOT NULL,
            name text NOT NULL,
            email text UNIQUE,
            status text CHECK (status IN ('Active', 'Inactive', 'Alumni')) DEFAULT 'Active'
        );
    END IF;
END $$;

-- 2. Link your current user account
DO $$
DECLARE
  v_user_id uuid;
BEGIN
  -- Find your user ID by email
  SELECT id INTO v_user_id FROM auth.users WHERE email = 'sahithi.thavishi@aurora.edu.in';

  IF v_user_id IS NOT NULL THEN
    -- Ensure profile exists in public.profiles
    INSERT INTO public.profiles (id, email, full_name, role)
    VALUES (v_user_id, 'sahithi.thavishi@aurora.edu.in', 'Test Student', 'student')
    ON CONFLICT (id) DO UPDATE SET role = 'student';

    -- Create or update the student record
    INSERT INTO public.students (profile_id, admission_no, name, email, status)
    VALUES (v_user_id, 'ADM' || floor(random() * 100000), 'Test Student', 'sahithi.thavishi@aurora.edu.in', 'Active')
    ON CONFLICT (email) DO UPDATE SET profile_id = v_user_id;
    
    RAISE NOTICE 'SUCCESS: Your account is now linked to a student record!';
  ELSE
    RAISE NOTICE 'ERROR: Account for sahithi.thavishi@aurora.edu.in not found. Please sign out and sign in again.';
  END IF;
END $$;
