-- Enable Row Level Security (RLS) is generally good practice, but we'll start simple for exploration
-- You can enable RLS later and add policies for fine-grained control.

create table if not exists public.profiles (
  id uuid references auth.users on delete cascade not null primary key,
  email text unique not null,
  full_name text,
  role text check (role in ('admin', 'student', 'mess_staff')) not null default 'student',
  avatar_url text,
  phone text,
  address text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table if not exists public.rooms (
  id bigint generated by default as identity primary key,
  room_number text not null unique,
  block text not null, 
  capacity int not null,
  current_occupancy int default 0,
  type text check (type in ('AC', 'Non-AC')) not null,
  status text check (status in ('Available', 'Occupied', 'Maintenance')) default 'Available',
  floor int,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table if not exists public.students (
  id bigint generated by default as identity primary key,
  profile_id uuid references public.profiles(id),
  admission_no text unique not null,
  name text not null,
  course text,
  year int,
  room_id bigint references public.rooms(id),
  parent_name text,
  parent_phone text,
  blood_group text,
  emergency_contact text,
  status text check (status in ('Active', 'Inactive', 'Alumni')) default 'Active',
  email text unique,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table if not exists public.complaints (
  id bigint generated by default as identity primary key,
  student_id bigint references public.students(id),
  user_id uuid references auth.users(id),
  title text not null,
  description text,
  category text check (category in ('Electrical', 'Plumbing', 'Furniture', 'Cleanliness', 'Other')),
  priority text check (priority in ('Low', 'Medium', 'High')),
  status text check (status in ('Pending', 'In Progress', 'Resolved')) default 'Pending',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  resolved_at timestamp with time zone
);

create table if not exists public.leaves (
  id bigint generated by default as identity primary key,
  student_id bigint references public.students(id),
  user_id uuid references auth.users(id),
  type text check (type in ('Outing', 'Leave')),
  reason text,
  start_date timestamp with time zone not null,
  end_date timestamp with time zone not null,
  status text check (status in ('Pending', 'Approved', 'Rejected')) default 'Pending',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table if not exists public.payments (
  id bigint generated by default as identity primary key,
  student_id bigint references public.students(id),
  amount decimal(10, 2) not null,
  type text check (type in ('Hostel Fee', 'Mess Fee', 'Fine', 'Other')),
  status text check (status in ('Paid', 'Pending', 'Failed')) default 'Pending',
  payment_date timestamp with time zone,
  transaction_id text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table if not exists public.mess_menu (
  id bigint generated by default as identity primary key,
  day_of_week text check (day_of_week in ('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday')),
  meal_type text check (meal_type in ('Breakfast', 'Lunch', 'Snacks', 'Dinner')),
  items text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(day_of_week, meal_type)
);

create table if not exists public.mess_inventory (
  id bigint generated by default as identity primary key,
  item_name text not null,
  quantity decimal(10, 2) not null,
  unit text not null,
  threshold decimal(10, 2),
  last_updated timestamp with time zone default timezone('utc'::text, now())
);

-- Function to handle new user signup automatically
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email, full_name, role)
  values (new.id, new.email, new.raw_user_meta_data->>'full_name', 'student');
  return new;
end;
$$ language plpgsql security definer;

-- Trigger to call the function on new user creation
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
